### ISSUE TITLE
xml file problem

### ISSUE THREAD

**Issue by qinglvding** [ajithabhks/SigMT#1]
Hello, I would like to ask how an. XML file is created

**Comment by ajithabhks** [comment]
Hi. Currently, this program only supports Metronix data. The Metronix measurements folder typically contains both time series files (.ats) and calibration information in an .xml file.

For example, [Data link](https://github.com/ajithabhks/SigMT/tree/main/data/test/meas_2019-08-29_16-27-00)

**Comment by Morphlinggod** [comment]
Hello，can you tell me how to get Metronix data？Which software can get both .ats and .xml file.
