### ISSUE TITLE
Problem With Input Data .ATS (Because of the senor coil Hx)

### ISSUE THREAD

**Issue by ZidanNaufal** [ajithabhks/sigmt#4]
Hello Mr. Ajit

I have some problem with some data data that cannot read. Like this:
![image](https://github.com/user-attachments/assets/824fb5ab-b568-459d-a106-89818ceb302c)

When I check it , it cannot read the number coil Hx:
![image](https://github.com/user-attachments/assets/e784174f-29ec-4f06-9e24-7095bc9f0c8c)

But when i check the time series it self, there is no problem with the sensor. And when I try it on another laptop it works

So what is the problem?

Regrad,
Zidan Naufal

**Comment by ajithabhks** [comment]
Hi Zidan Naufal,

This issue can occur in two cases:

1. Coil was not detected during the instrument installation.
2. Coil calibration data block is missing from the XML file.

Regards,
Ajithabh
